export enum ApiErrorCode {
	INTERNAL_ERROR = 'INTERNAL_ERROR',
	VALIDATION_ERROR = 'VALIDATION_ERROR',
	NOT_FOUND = 'NOT_FOUND',
	UNAUTHORIZED = 'UNAUTHORIZED',
	FORBIDDEN = 'FORBIDDEN',
	BAD_REQUEST = 'BAD_REQUEST',
	AUTH_FAILURE = 'AUTH_FAILURE'
}
